name: canvas_batch_change_dates
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python-dotenv
  - termcolor
  - requests
  - jupyter
  - pandas
  - pip
  - pip:
      - canvasapi
